### ISSUE TITLE
Issue writing aligned_tilt_series.star

### ISSUE THREAD

**Issue by EuanPyle** [alisterburt/tomo_preprocessing#40]
When running wrapper outside of relion (ie on the command line with relion_tomo_align_tilt_series) a aligned_tilt_series.star is not written. With latest update to tomo_model, aligned_tilt_series.star is written (mostly correctly) but is titled data_ as opposed to data_global. Not sure if this is an issue on our end or rln end

**Comment by alisterburt** [comment]
any ideas why? 

this is the conditional for when that func is run
https://github.com/alisterburt/tomo_preprocessing/blob/273787ce7901a1259704424fe02c2ae959d8d8d9/tomography_preprocessing/tilt_series_alignment/aretomo/batch.py#L68-L73

that runs this
https://github.com/alisterburt/tomo_preprocessing/blob/273787ce7901a1259704424fe02c2ae959d8d8d9/tomography_preprocessing/tilt_series_alignment/aretomo/_utils.py#L6-L19

which should actually run
https://github.com/alisterburt/tomo_preprocessing/blob/273787ce7901a1259704424fe02c2ae959d8d8d9/tomography_preprocessing/tilt_series_alignment/_job_utils.py#L91-L114

So we should update there...

> data_ as opposed to data_global. Not sure if this is an issue on our end or rln end

This is an issue on the rln end -> let's update that ourselves :)

**Comment by EuanPyle** [comment]
Ah I'll fix that.

I can let Sjors know re: the data_global thing, altho feel like I'm over reporting bugs and everyone will be sick of me fairly soon :-|

**Comment by EuanPyle** [comment]
Found the problem finally with our wrapper not generating aligned_tilt_series.star. Had a bit of an unsuccessful day, so very happy with this small win!

**Comment by alisterburt** [comment]
what was the issue?!

RELION writes that file itself actually which means there is some irritating decoupling of where things are defined vs where they are interpreted - I made our version a CLI program that could be called at the end but sjors seemed to prefer keeping that in the cpp stuff 🤷🏼‍♂️ 

We should probably remove this from our code and make ours capable only of aligning a single ts at a time
