### ISSUE TITLE
Tomogram Generation Comparison

### ISSUE THREAD

**Issue by EuanPyle** [alisterburt/tomo_preprocessing#43]
So I've got some nice in situ data which I've been using to test the pipeline. It's now working really nicely with no obvious errors which is nice. One area which needs work is the tomograms produced by rln. For reference, here is a reconstruction of the data where the alignment was done in standalone AreTomo (AT) with local alignments and the tomogram produced by AT with SIRT like filtering:
![All_AT](https://user-images.githubusercontent.com/19735492/174312596-7aabba4a-e4e6-489c-94ea-c30053c258e5.png)

Which looks really nice. With rln, the reconstructions with standard settings don't look so good. The alignments with IMOD (image 1) and AT (image 2) look similar quality: 
![IMOD_CTF](https://user-images.githubusercontent.com/19735492/174312779-4fbe2817-1323-4539-9e29-97bee12b17a1.png)
![AreTomo_CTF](https://user-images.githubusercontent.com/19735492/174312790-1d54f49d-b024-40b8-8e28-5c710633a9e8.png)

When using the --noctf flag, the tomogram becomes clearer, but still not to the quality of AT:
![IMOD_No_CTF](https://user-images.githubusercontent.com/19735492/174312951-03a9d73f-4c12-43bc-b5bb-74f29a5a36dd.png)
![AreTomo_No_CTF](https://user-images.githubusercontent.com/19735492/174312991-cfeb1af8-df33-4f5b-83c9-5c34c4e44de5.png)

I think it's pretty crucial for in situ data that the tomos look better than they do at the moment. I think the noctf ones look better but still not of the right quality. A SIRT like filter option seems p essential to add imo, and maybe noctf could be on by default (with an: Add CTF Devolution? option to take it off). I'm still looking into routines to add cryoCARE for denoising as well.

**Comment by alisterburt** [comment]
Thanks for the direct comparisons here @EuanPyle - couple of things to untangle...

Is it the local motion correction that's having a large effect on the tomogram quality, or is it the filtering/reconstruction method (SART I think)? Incorporating the local motion is a huge barrier and not something we can take on lightly, it would significantly complicate (potentially make impossible) the direct use of these tomograms with existing relion code for fancy refinements. We can modify the filtering relatively easily if that's the most important thing (although I don't actually know how).

is your rlnTomoHand correct/did you try the other one? This could also be why CTF makes things worse in your case...

**Comment by EuanPyle** [comment]
So adding correction for tilt angle offset makes a big improvement in the AreTomo tomogram quality, so that's something! Will ask for it to be incorporated into the RELION GUI as its information is included in the xf file. I'll test flipping the hand for CTF and let you know. I think both SART and local correction help, but agreed re: local motion. The tomos still look very good without local so I think SART makes a significant improvement and is definitely worth integrating. I'll try and have a look at the rln code to see how it can be implemented.

**Comment by inter1965** [comment]
Just encounter the same problem when reconstructing via relion4. Compared to SART reconstruction, it's hardly to pick from relion's reconstruction. Looking forward to a solution for that.
> So adding correction for tilt angle offset makes a big improvement in the AreTomo tomogram quality, so that's something! Will ask for it to be incorporated into the RELION GUI as its information is included in the xf file. I'll test flipping the hand for CTF and let you know. I think both SART and local correction help, but agreed re: local motion. The tomos still look very good without local so I think SART makes a significant improvement and is definitely worth integrating. I'll try and have a look at the rln code to see how it can be implemented.

**Comment by alisterburt** [comment]
I'll be looking into this more today - I think there is a problem with the interpretation of the shifts

**Comment by EuanPyle** [comment]
> @inter1965 @EuanPyle could you pull tomo model, recompile, run tsa and reconstruct tomograms? This should now be fixed - the wrong data label was being used for the pixel size so shifts were calculated incorrectly 

Will do tomorrow, thanks!

**Comment by EuanPyle** [comment]
The AreTomo results look the same (as in 100% the same), just trying IMOD Patch Tracking now

**Comment by EuanPyle** [comment]
Tomo rec from patch tracking also looks the same (mild difference in contrast, as in, I have to click auto in 3dmod to adjust the brightness, but quality looks exactly the same)

**Comment by alisterburt** [comment]
Just to check, your motion corrected images weren't binned?

**Comment by alisterburt** [comment]
It's expected that things would look exactly the same if no binning was applied during motion correction - could you ask Shawn about the rotation center of tilt images in AreTomo?

**Comment by EuanPyle** [comment]
Yeah, no binning during motion cor for this dataset, so that would explain it! Sure, what specifically about the rotation center?

**Comment by alisterburt** [comment]
I suspected the quality decrease was due to incorrect shifts - shifts were only incorrect if images were binned during motion correction

**Comment by alisterburt** [comment]
Just where the rotation is in his aligned tilt-series, imod is (n-1)/2 (zero indexed)

**Comment by EuanPyle** [comment]
cool, have emailed!

**Comment by EuanPyle** [comment]
"AreTomo uses n*0.5 in zero-indexed coordinate system"

**Comment by alisterburt** [comment]
closing because development has moved to relion repo
