### ISSUE TITLE
MotionCor2 No Longer Working

### ISSUE THREAD

**Issue by EuanPyle** [alisterburt/tomo_preprocessing#49]
https://github.com/alisterburt/tomo_preprocessing/blob/217bd46a5ebe7147dd7edd729c6a8e2dc9e76d7d/tomography_preprocessing/import_tilt_series/serialem.py#L103-L105

There's an issue here. rln now raises an error upon MotionCor2 complaining that rlnTomoTiltSeriesPixelSize is not present in global. When I alter this line to switch rlnMicrographOriginalPixelSize to rlnTomoTiltSeriesPixelSize, rln complains that the input STAR file does not contain the pixel size. If I add both rlnMicrographOriginalPixelSize and rlnTomoTiltSeriesPixelSize to the global star file, it still complains that the input STAR file does not contain the pixel size.

**Comment by alisterburt** [comment]
🙈 this will be a consequence of how Sjors updated pixel size handling in relion - the problem is over there, I will message him

**Comment by EuanPyle** [comment]
Do we want to keep it as rlnMicrographOriginalPixelSize in tomo_PP? Having some success trying to fix this in rlni itself

**Comment by alisterburt** [comment]
Sorry I should have updated here - Sjors is going to fix this early next week, we need to track both the movie pixel size and the original pixel size in the tomogram set on the cpp side which isn't done yet and has led to all of these errors

**Comment by EuanPyle** [comment]
cheers!

**Comment by EuanPyle** [comment]
Fixed :)

**Comment by alisterburt** [comment]
pew pew
